### PR TITLE
Add STASH_REF_CHANGES environment variable.

### PR DESCRIPTION
**Pull request by exception0x876**
This variable is useful for performing an action only if specific branches have changed.

### CODE REVIEW

**Comment by seletskiy** [comment]
@exception0x876: Pls, remove trailing space from variable value.

**Comment by bturner** [comment]
Not my app, so not my decision, but why would you add these like this? External hooks are _streamed_ the ref changes, which includes all the IDs, on their stdin. Passing ref IDs in the environment is wasteful/unnecessary.

More importantly, though, passing them in the environment is _dangerous_. When Bitbucket Server is hosted on Windows, the _total environment block_ (all variables together) has a hard size limit. This code doesn't check how many IDs it's setting, or how large the resulting variable is. An initial push for a new repository created from an existing repository could _easily_ exceed Windows's environment limit, causing the script to fail to start.

If your script wants to react to specific refs, read stdin and check the ref IDs there.

**Comment by seletskiy** [comment]
@bturner: that is good point and this change was not added to upstream version (hence PR is open).

**Comment by seletskiy** [comment]
Script stdin could be used to get ref changes.

**Pull request closed without merging**
